import type { ThemeDefinition } from '../types';

export const themes: Record<string, ThemeDefinition> = {
  // ============================
  // Default: Neobrutalist / Lo-Fi
  // ============================
  'neobrutalist-light': {
    id: 'neobrutalist-light',
    name: 'Neobrutalist',
    variant: 'light',
    colors: {
      background: '#f5f0e8',
      surface: '#ffffff',
      surfaceHover: '#faf8f4',
      primary: '#ff6b6b',
      secondary: '#4ecdc4',
      accent: '#ffe66d',
      text: '#2d2d2d',
      textMuted: '#6b6b6b',
      border: '#2d2d2d',
      shadow: '#2d2d2d',
      cardBg: '#ffffff',
      cardBorder: '#2d2d2d',
      connectionLine: '#2d2d2d',
      selectionStroke: '#ff6b6b',
      danger: '#ff4757',
      success: '#2ed573',
    },
    typography: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', 'Courier', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '4px',
      borderRadiusLg: '8px',
      borderWidth: '3px',
      shadowStyle: '4px 4px 0px #2d2d2d',
      buttonStyle: 'flat',
      cardStyle: 'sharp',
    },
  },

  'neobrutalist-dark': {
    id: 'neobrutalist-dark',
    name: 'Neobrutalist Dark',
    variant: 'dark',
    colors: {
      background: '#1a1a2e',
      surface: '#16213e',
      surfaceHover: '#1a2744',
      primary: '#ff6b6b',
      secondary: '#4ecdc4',
      accent: '#ffe66d',
      text: '#e8e8e8',
      textMuted: '#9a9a9a',
      border: '#e8e8e8',
      shadow: '#000000',
      cardBg: '#16213e',
      cardBorder: '#e8e8e8',
      connectionLine: '#e8e8e8',
      selectionStroke: '#ff6b6b',
      danger: '#ff4757',
      success: '#2ed573',
    },
    typography: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', 'Courier', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '4px',
      borderRadiusLg: '8px',
      borderWidth: '3px',
      shadowStyle: '4px 4px 0px #000000',
      buttonStyle: 'flat',
      cardStyle: 'sharp',
    },
  },

  // ============================
  // Old OS / Vaporwave
  // ============================
  'oldos-light': {
    id: 'oldos-light',
    name: 'Old OS',
    variant: 'light',
    colors: {
      background: '#c0c0c0',
      surface: '#dfdfdf',
      surfaceHover: '#e8e8e8',
      primary: '#000080',
      secondary: '#008080',
      accent: '#ffff00',
      text: '#000000',
      textMuted: '#444444',
      border: '#808080',
      shadow: '#000000',
      cardBg: '#ffffff',
      cardBorder: '#808080',
      connectionLine: '#000080',
      selectionStroke: '#000080',
      danger: '#ff0000',
      success: '#008000',
    },
    typography: {
      fontFamily: "'Courier New', 'VT323', monospace",
      fontFamilyMono: "'Courier New', 'VT323', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.4,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '0px',
      borderRadiusLg: '0px',
      borderWidth: '2px',
      shadowStyle: 'inset -1px -1px 0px #808080, inset 1px 1px 0px #ffffff',
      buttonStyle: 'bevel',
      cardStyle: 'sharp',
    },
  },

  'oldos-dark': {
    id: 'oldos-dark',
    name: 'Vaporwave',
    variant: 'dark',
    colors: {
      background: '#0a0a1a',
      surface: '#1a0a2e',
      surfaceHover: '#2a1a3e',
      primary: '#ff71ce',
      secondary: '#01cdfe',
      accent: '#05ffa1',
      text: '#ffffff',
      textMuted: '#b967ff',
      border: '#b967ff',
      shadow: '#000000',
      cardBg: '#1a0a2e',
      cardBorder: '#b967ff',
      connectionLine: '#ff71ce',
      selectionStroke: '#01cdfe',
      danger: '#ff0044',
      success: '#05ffa1',
    },
    typography: {
      fontFamily: "'Courier New', 'VT323', monospace",
      fontFamilyMono: "'Courier New', 'VT323', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.4,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '0px',
      borderRadiusLg: '0px',
      borderWidth: '2px',
      shadowStyle: '0 0 10px #b967ff, 0 0 20px #b967ff40',
      buttonStyle: 'bevel',
      cardStyle: 'neon',
    },
  },

  // ============================
  // Academia / Manuscript
  // ============================
  'academia-light': {
    id: 'academia-light',
    name: 'Manuscript',
    variant: 'light',
    colors: {
      background: '#fdf6e3',
      surface: '#faf3dc',
      surfaceHover: '#f7efce',
      primary: '#8b4513',
      secondary: '#556b2f',
      accent: '#b8860b',
      text: '#3c2415',
      textMuted: '#8b7355',
      border: '#8b7355',
      shadow: '#8b735540',
      cardBg: '#fdf8ed',
      cardBorder: '#8b7355',
      connectionLine: '#8b4513',
      selectionStroke: '#8b4513',
      danger: '#a0522d',
      success: '#556b2f',
    },
    typography: {
      fontFamily: "'Georgia', 'Garamond', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.7,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '1rem', lg: '1.25rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '2px',
      borderRadiusLg: '4px',
      borderWidth: '1px',
      shadowStyle: '2px 2px 8px #8b735530',
      svgFilter: 'url(#ink-stroke)',
      buttonStyle: 'flat',
      cardStyle: 'hand-drawn',
    },
  },

  'academia-dark': {
    id: 'academia-dark',
    name: 'Dark Manuscript',
    variant: 'dark',
    colors: {
      background: '#2c2416',
      surface: '#3c3020',
      surfaceHover: '#4a3c28',
      primary: '#d4a574',
      secondary: '#8fbc8f',
      accent: '#daa520',
      text: '#e8dcc8',
      textMuted: '#a89880',
      border: '#a89880',
      shadow: '#00000060',
      cardBg: '#3c3020',
      cardBorder: '#a89880',
      connectionLine: '#d4a574',
      selectionStroke: '#daa520',
      danger: '#cd853f',
      success: '#8fbc8f',
    },
    typography: {
      fontFamily: "'Georgia', 'Garamond', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.7,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '1rem', lg: '1.25rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '2px',
      borderRadiusLg: '4px',
      borderWidth: '1px',
      shadowStyle: '2px 2px 8px #00000040',
      svgFilter: 'url(#ink-stroke)',
      buttonStyle: 'flat',
      cardStyle: 'hand-drawn',
    },
  },

  // ============================
  // Futuristic / Cyberpunk
  // ============================
  'cyberpunk-light': {
    id: 'cyberpunk-light',
    name: 'Tech Light',
    variant: 'light',
    colors: {
      background: '#e8edf5',
      surface: '#f0f4fc',
      surfaceHover: '#dce3f0',
      primary: '#0066ff',
      secondary: '#00ccaa',
      accent: '#ff3366',
      text: '#0a0a1a',
      textMuted: '#5a5a7a',
      border: '#0066ff40',
      shadow: '#0066ff20',
      cardBg: '#ffffff',
      cardBorder: '#0066ff40',
      connectionLine: '#0066ff',
      selectionStroke: '#ff3366',
      danger: '#ff3366',
      success: '#00ccaa',
    },
    typography: {
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.65rem', sm: '0.75rem', md: '0.85rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #0066ff15',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  'cyberpunk-dark': {
    id: 'cyberpunk-dark',
    name: 'Cyberpunk',
    variant: 'dark',
    colors: {
      background: '#0a0a1a',
      surface: '#111128',
      surfaceHover: '#1a1a38',
      primary: '#00ff88',
      secondary: '#00ccff',
      accent: '#ff0066',
      text: '#e0e0ff',
      textMuted: '#8888aa',
      border: '#00ff8840',
      shadow: '#00ff8820',
      cardBg: '#111128',
      cardBorder: '#00ff8860',
      connectionLine: '#00ff88',
      selectionStroke: '#ff0066',
      danger: '#ff0066',
      success: '#00ff88',
    },
    typography: {
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.65rem', sm: '0.75rem', md: '0.85rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 0 15px #00ff8830, 0 0 30px #00ff8810',
      buttonStyle: 'glow',
      cardStyle: 'neon',
    },
  },

  // ============================
  // Natural / Zen
  // ============================
  'zen-light': {
    id: 'zen-light',
    name: 'Zen',
    variant: 'light',
    colors: {
      background: '#f0ebe3',
      surface: '#f7f3ed',
      surfaceHover: '#ece5d8',
      primary: '#7c8c6e',
      secondary: '#c4956a',
      accent: '#d4a574',
      text: '#3d3d3d',
      textMuted: '#8a8a7a',
      border: '#c8c0b0',
      shadow: '#8a8a7a30',
      cardBg: '#faf7f2',
      cardBorder: '#c8c0b0',
      connectionLine: '#7c8c6e',
      selectionStroke: '#c4956a',
      danger: '#c87060',
      success: '#7c8c6e',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'SF Mono', 'Consolas', monospace",
      fontWeight: 300,
      fontWeightBold: 600,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '16px',
      borderRadiusLg: '24px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #8a8a7a15',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  'zen-dark': {
    id: 'zen-dark',
    name: 'Dark Zen',
    variant: 'dark',
    colors: {
      background: '#1a1e1a',
      surface: '#252a24',
      surfaceHover: '#2e342c',
      primary: '#8fa880',
      secondary: '#c4956a',
      accent: '#d4a574',
      text: '#d8d4c8',
      textMuted: '#8a8878',
      border: '#4a4a3e',
      shadow: '#00000040',
      cardBg: '#252a24',
      cardBorder: '#4a4a3e',
      connectionLine: '#8fa880',
      selectionStroke: '#c4956a',
      danger: '#c87060',
      success: '#8fa880',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'SF Mono', 'Consolas', monospace",
      fontWeight: 300,
      fontWeightBold: 600,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '16px',
      borderRadiusLg: '24px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #00000030',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Nord - Scandinavian minimalism
  // ============================
  'nord-light': {
    id: 'nord-light',
    name: 'Nord Light',
    variant: 'light',
    colors: {
      background: '#eceff4',
      surface: '#e5e9f0',
      surfaceHover: '#d8dee9',
      primary: '#5e81ac',
      secondary: '#88c0d0',
      accent: '#ebcb8b',
      text: '#2e3440',
      textMuted: '#4c566a',
      border: '#d8dee9',
      shadow: '#4c566a20',
      cardBg: '#ffffff',
      cardBorder: '#d8dee9',
      connectionLine: '#5e81ac',
      selectionStroke: '#88c0d0',
      danger: '#bf616a',
      success: '#a3be8c',
    },
    typography: {
      fontFamily: "'Inter', 'system-ui', '-apple-system', sans-serif",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '8px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 1px 6px #4c566a15',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  'nord-dark': {
    id: 'nord-dark',
    name: 'Nord Dark',
    variant: 'dark',
    colors: {
      background: '#2e3440',
      surface: '#3b4252',
      surfaceHover: '#434c5e',
      primary: '#88c0d0',
      secondary: '#81a1c1',
      accent: '#ebcb8b',
      text: '#eceff4',
      textMuted: '#d8dee9',
      border: '#4c566a',
      shadow: '#00000040',
      cardBg: '#3b4252',
      cardBorder: '#4c566a',
      connectionLine: '#88c0d0',
      selectionStroke: '#81a1c1',
      danger: '#bf616a',
      success: '#a3be8c',
    },
    typography: {
      fontFamily: "'Inter', 'system-ui', '-apple-system', sans-serif",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '8px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 2px 8px #00000030',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Solarized - Classic warm tones
  // ============================
  'solarized-light': {
    id: 'solarized-light',
    name: 'Solarized Light',
    variant: 'light',
    colors: {
      background: '#fdf6e3',
      surface: '#eee8d5',
      surfaceHover: '#e6dfca',
      primary: '#268bd2',
      secondary: '#2aa198',
      accent: '#b58900',
      text: '#657b83',
      textMuted: '#93a1a1',
      border: '#93a1a1',
      shadow: '#00000015',
      cardBg: '#fdf6e3',
      cardBorder: '#93a1a1',
      connectionLine: '#268bd2',
      selectionStroke: '#cb4b16',
      danger: '#dc322f',
      success: '#859900',
    },
    typography: {
      fontFamily: "'Source Sans Pro', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'Source Code Pro', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.55,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '10px',
      borderWidth: '1px',
      shadowStyle: '0 1px 4px #00000010',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  'solarized-dark': {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    variant: 'dark',
    colors: {
      background: '#002b36',
      surface: '#073642',
      surfaceHover: '#0a4050',
      primary: '#268bd2',
      secondary: '#2aa198',
      accent: '#b58900',
      text: '#839496',
      textMuted: '#586e75',
      border: '#586e75',
      shadow: '#00000040',
      cardBg: '#073642',
      cardBorder: '#586e75',
      connectionLine: '#268bd2',
      selectionStroke: '#cb4b16',
      danger: '#dc322f',
      success: '#859900',
    },
    typography: {
      fontFamily: "'Source Sans Pro', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'Source Code Pro', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.55,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '10px',
      borderWidth: '1px',
      shadowStyle: '0 2px 8px #00000030',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Pastel Dream - Soft & playful
  // ============================
  'pastel-light': {
    id: 'pastel-light',
    name: 'Pastel Dream',
    variant: 'light',
    colors: {
      background: '#fef7ff',
      surface: '#fdf0f5',
      surfaceHover: '#fce4ee',
      primary: '#c084fc',
      secondary: '#67e8f9',
      accent: '#fbbf24',
      text: '#4a3560',
      textMuted: '#9b8ab8',
      border: '#e2c4f0',
      shadow: '#c084fc15',
      cardBg: '#ffffff',
      cardBorder: '#e2c4f0',
      connectionLine: '#c084fc',
      selectionStroke: '#f472b6',
      danger: '#fb7185',
      success: '#86efac',
    },
    typography: {
      fontFamily: "'Nunito', 'Quicksand', 'system-ui', sans-serif",
      fontFamilyMono: "'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '20px',
      borderRadiusLg: '28px',
      borderWidth: '2px',
      shadowStyle: '0 4px 16px #c084fc12',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // OLED Black - True black for AMOLED
  // ============================
  'oled-dark': {
    id: 'oled-dark',
    name: 'OLED Black',
    variant: 'dark',
    colors: {
      background: '#000000',
      surface: '#0a0a0a',
      surfaceHover: '#141414',
      primary: '#818cf8',
      secondary: '#34d399',
      accent: '#fbbf24',
      text: '#f0f0f0',
      textMuted: '#6b7280',
      border: '#1f1f1f',
      shadow: '#00000080',
      cardBg: '#0a0a0a',
      cardBorder: '#1f1f1f',
      connectionLine: '#818cf8',
      selectionStroke: '#f472b6',
      danger: '#ef4444',
      success: '#34d399',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'SF Mono', 'JetBrains Mono', monospace",
      fontWeight: 300,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '12px',
      borderRadiusLg: '16px',
      borderWidth: '1px',
      shadowStyle: '0 0 0 1px #1f1f1f',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Dracula - Popular dark theme
  // ============================
  'dracula-dark': {
    id: 'dracula-dark',
    name: 'Dracula',
    variant: 'dark',
    colors: {
      background: '#282a36',
      surface: '#44475a',
      surfaceHover: '#4e5270',
      primary: '#bd93f9',
      secondary: '#8be9fd',
      accent: '#f1fa8c',
      text: '#f8f8f2',
      textMuted: '#6272a4',
      border: '#6272a4',
      shadow: '#00000040',
      cardBg: '#44475a',
      cardBorder: '#6272a4',
      connectionLine: '#bd93f9',
      selectionStroke: '#ff79c6',
      danger: '#ff5555',
      success: '#50fa7b',
    },
    typography: {
      fontFamily: "'Fira Sans', 'system-ui', sans-serif",
      fontFamilyMono: "'Fira Code', 'JetBrains Mono', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '8px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 2px 8px #00000030',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Ocean Breeze - Cool & refreshing
  // ============================
  'ocean-light': {
    id: 'ocean-light',
    name: 'Ocean Breeze',
    variant: 'light',
    colors: {
      background: '#f0f9ff',
      surface: '#e0f2fe',
      surfaceHover: '#bae6fd',
      primary: '#0284c7',
      secondary: '#06b6d4',
      accent: '#f59e0b',
      text: '#0c4a6e',
      textMuted: '#64748b',
      border: '#7dd3fc',
      shadow: '#0284c715',
      cardBg: '#ffffff',
      cardBorder: '#7dd3fc',
      connectionLine: '#0284c7',
      selectionStroke: '#f59e0b',
      danger: '#ef4444',
      success: '#22c55e',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Segoe UI', sans-serif",
      fontFamilyMono: "'Cascadia Code', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '10px',
      borderRadiusLg: '16px',
      borderWidth: '1px',
      shadowStyle: '0 2px 10px #0284c710',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Sunset Warmth - Golden hour
  // ============================
  'sunset-light': {
    id: 'sunset-light',
    name: 'Sunset',
    variant: 'light',
    colors: {
      background: '#fff7ed',
      surface: '#ffedd5',
      surfaceHover: '#fed7aa',
      primary: '#ea580c',
      secondary: '#d946ef',
      accent: '#eab308',
      text: '#431407',
      textMuted: '#9a3412',
      border: '#fdba74',
      shadow: '#ea580c10',
      cardBg: '#fffbf5',
      cardBorder: '#fdba74',
      connectionLine: '#ea580c',
      selectionStroke: '#d946ef',
      danger: '#dc2626',
      success: '#16a34a',
    },
    typography: {
      fontFamily: "'Georgia', 'Cambria', serif",
      fontFamilyMono: "'Courier New', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '8px',
      borderRadiusLg: '14px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #ea580c08',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  // ============================
  // Aurora - Northern lights dark
  // ============================
  'aurora-dark': {
    id: 'aurora-dark',
    name: 'Aurora',
    variant: 'dark',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      surfaceHover: '#334155',
      primary: '#22d3ee',
      secondary: '#a78bfa',
      accent: '#34d399',
      text: '#e2e8f0',
      textMuted: '#94a3b8',
      border: '#334155',
      shadow: '#00000050',
      cardBg: '#1e293b',
      cardBorder: '#334155',
      connectionLine: '#22d3ee',
      selectionStroke: '#a78bfa',
      danger: '#f87171',
      success: '#34d399',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 600,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.15rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '10px',
      borderRadiusLg: '16px',
      borderWidth: '1px',
      shadowStyle: '0 0 20px #22d3ee10, 0 4px 12px #00000020',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },
};
