import type { ThemeDefinition } from '../types';

export const themes: Record<string, ThemeDefinition> = {
  // ============================
  // Default: Neobrutalist / Lo-Fi
  // ============================
  'neobrutalist-light': {
    id: 'neobrutalist-light',
    name: 'Neobrutalist',
    variant: 'light',
    colors: {
      background: '#f5f0e8',
      surface: '#ffffff',
      surfaceHover: '#faf8f4',
      primary: '#ff6b6b',
      secondary: '#4ecdc4',
      accent: '#ffe66d',
      text: '#2d2d2d',
      textMuted: '#6b6b6b',
      border: '#2d2d2d',
      shadow: '#2d2d2d',
      cardBg: '#ffffff',
      cardBorder: '#2d2d2d',
      connectionLine: '#2d2d2d',
      selectionStroke: '#ff6b6b',
      danger: '#ff4757',
      success: '#2ed573',
    },
    typography: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', 'Courier', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '4px',
      borderRadiusLg: '8px',
      borderWidth: '3px',
      shadowStyle: '4px 4px 0px #2d2d2d',
      buttonStyle: 'flat',
      cardStyle: 'sharp',
    },
  },

  'neobrutalist-dark': {
    id: 'neobrutalist-dark',
    name: 'Neobrutalist Dark',
    variant: 'dark',
    colors: {
      background: '#1a1a2e',
      surface: '#16213e',
      surfaceHover: '#1a2744',
      primary: '#ff6b6b',
      secondary: '#4ecdc4',
      accent: '#ffe66d',
      text: '#e8e8e8',
      textMuted: '#9a9a9a',
      border: '#e8e8e8',
      shadow: '#000000',
      cardBg: '#16213e',
      cardBorder: '#e8e8e8',
      connectionLine: '#e8e8e8',
      selectionStroke: '#ff6b6b',
      danger: '#ff4757',
      success: '#2ed573',
    },
    typography: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', 'Courier', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.95rem', lg: '1.2rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '4px',
      borderRadiusLg: '8px',
      borderWidth: '3px',
      shadowStyle: '4px 4px 0px #000000',
      buttonStyle: 'flat',
      cardStyle: 'sharp',
    },
  },

  // ============================
  // Old OS / Vaporwave
  // ============================
  'oldos-light': {
    id: 'oldos-light',
    name: 'Old OS',
    variant: 'light',
    colors: {
      background: '#c0c0c0',
      surface: '#dfdfdf',
      surfaceHover: '#e8e8e8',
      primary: '#000080',
      secondary: '#008080',
      accent: '#ffff00',
      text: '#000000',
      textMuted: '#444444',
      border: '#808080',
      shadow: '#000000',
      cardBg: '#ffffff',
      cardBorder: '#808080',
      connectionLine: '#000080',
      selectionStroke: '#000080',
      danger: '#ff0000',
      success: '#008000',
    },
    typography: {
      fontFamily: "'Courier New', 'VT323', monospace",
      fontFamilyMono: "'Courier New', 'VT323', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.4,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '0px',
      borderRadiusLg: '0px',
      borderWidth: '2px',
      shadowStyle: 'inset -1px -1px 0px #808080, inset 1px 1px 0px #ffffff',
      buttonStyle: 'bevel',
      cardStyle: 'sharp',
    },
  },

  'oldos-dark': {
    id: 'oldos-dark',
    name: 'Vaporwave',
    variant: 'dark',
    colors: {
      background: '#0a0a1a',
      surface: '#1a0a2e',
      surfaceHover: '#2a1a3e',
      primary: '#ff71ce',
      secondary: '#01cdfe',
      accent: '#05ffa1',
      text: '#ffffff',
      textMuted: '#b967ff',
      border: '#b967ff',
      shadow: '#000000',
      cardBg: '#1a0a2e',
      cardBorder: '#b967ff',
      connectionLine: '#ff71ce',
      selectionStroke: '#01cdfe',
      danger: '#ff0044',
      success: '#05ffa1',
    },
    typography: {
      fontFamily: "'Courier New', 'VT323', monospace",
      fontFamilyMono: "'Courier New', 'VT323', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.4,
      fontSize: { xs: '0.7rem', sm: '0.8rem', md: '0.9rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '0px',
      borderRadiusLg: '0px',
      borderWidth: '2px',
      shadowStyle: '0 0 10px #b967ff, 0 0 20px #b967ff40',
      buttonStyle: 'bevel',
      cardStyle: 'neon',
    },
  },

  // ============================
  // Academia / Manuscript
  // ============================
  'academia-light': {
    id: 'academia-light',
    name: 'Manuscript',
    variant: 'light',
    colors: {
      background: '#fdf6e3',
      surface: '#faf3dc',
      surfaceHover: '#f7efce',
      primary: '#8b4513',
      secondary: '#556b2f',
      accent: '#b8860b',
      text: '#3c2415',
      textMuted: '#8b7355',
      border: '#8b7355',
      shadow: '#8b735540',
      cardBg: '#fdf8ed',
      cardBorder: '#8b7355',
      connectionLine: '#8b4513',
      selectionStroke: '#8b4513',
      danger: '#a0522d',
      success: '#556b2f',
    },
    typography: {
      fontFamily: "'Georgia', 'Garamond', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.7,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '1rem', lg: '1.25rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '2px',
      borderRadiusLg: '4px',
      borderWidth: '1px',
      shadowStyle: '2px 2px 8px #8b735530',
      svgFilter: 'url(#ink-stroke)',
      buttonStyle: 'flat',
      cardStyle: 'hand-drawn',
    },
  },

  'academia-dark': {
    id: 'academia-dark',
    name: 'Dark Manuscript',
    variant: 'dark',
    colors: {
      background: '#2c2416',
      surface: '#3c3020',
      surfaceHover: '#4a3c28',
      primary: '#d4a574',
      secondary: '#8fbc8f',
      accent: '#daa520',
      text: '#e8dcc8',
      textMuted: '#a89880',
      border: '#a89880',
      shadow: '#00000060',
      cardBg: '#3c3020',
      cardBorder: '#a89880',
      connectionLine: '#d4a574',
      selectionStroke: '#daa520',
      danger: '#cd853f',
      success: '#8fbc8f',
    },
    typography: {
      fontFamily: "'Georgia', 'Garamond', 'Times New Roman', serif",
      fontFamilyMono: "'Courier New', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.7,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '1rem', lg: '1.25rem', xl: '1.6rem', xxl: '2.2rem' },
    },
    decorations: {
      borderRadius: '2px',
      borderRadiusLg: '4px',
      borderWidth: '1px',
      shadowStyle: '2px 2px 8px #00000040',
      svgFilter: 'url(#ink-stroke)',
      buttonStyle: 'flat',
      cardStyle: 'hand-drawn',
    },
  },

  // ============================
  // Futuristic / Cyberpunk
  // ============================
  'cyberpunk-light': {
    id: 'cyberpunk-light',
    name: 'Tech Light',
    variant: 'light',
    colors: {
      background: '#e8edf5',
      surface: '#f0f4fc',
      surfaceHover: '#dce3f0',
      primary: '#0066ff',
      secondary: '#00ccaa',
      accent: '#ff3366',
      text: '#0a0a1a',
      textMuted: '#5a5a7a',
      border: '#0066ff40',
      shadow: '#0066ff20',
      cardBg: '#ffffff',
      cardBorder: '#0066ff40',
      connectionLine: '#0066ff',
      selectionStroke: '#ff3366',
      danger: '#ff3366',
      success: '#00ccaa',
    },
    typography: {
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.65rem', sm: '0.75rem', md: '0.85rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #0066ff15',
      buttonStyle: 'flat',
      cardStyle: 'rounded',
    },
  },

  'cyberpunk-dark': {
    id: 'cyberpunk-dark',
    name: 'Cyberpunk',
    variant: 'dark',
    colors: {
      background: '#0a0a1a',
      surface: '#111128',
      surfaceHover: '#1a1a38',
      primary: '#00ff88',
      secondary: '#00ccff',
      accent: '#ff0066',
      text: '#e0e0ff',
      textMuted: '#8888aa',
      border: '#00ff8840',
      shadow: '#00ff8820',
      cardBg: '#111128',
      cardBorder: '#00ff8860',
      connectionLine: '#00ff88',
      selectionStroke: '#ff0066',
      danger: '#ff0066',
      success: '#00ff88',
    },
    typography: {
      fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      fontFamilyMono: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: 400,
      fontWeightBold: 700,
      lineHeight: 1.5,
      fontSize: { xs: '0.65rem', sm: '0.75rem', md: '0.85rem', lg: '1.1rem', xl: '1.4rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '6px',
      borderRadiusLg: '12px',
      borderWidth: '1px',
      shadowStyle: '0 0 15px #00ff8830, 0 0 30px #00ff8810',
      buttonStyle: 'glow',
      cardStyle: 'neon',
    },
  },

  // ============================
  // Natural / Zen
  // ============================
  'zen-light': {
    id: 'zen-light',
    name: 'Zen',
    variant: 'light',
    colors: {
      background: '#f0ebe3',
      surface: '#f7f3ed',
      surfaceHover: '#ece5d8',
      primary: '#7c8c6e',
      secondary: '#c4956a',
      accent: '#d4a574',
      text: '#3d3d3d',
      textMuted: '#8a8a7a',
      border: '#c8c0b0',
      shadow: '#8a8a7a30',
      cardBg: '#faf7f2',
      cardBorder: '#c8c0b0',
      connectionLine: '#7c8c6e',
      selectionStroke: '#c4956a',
      danger: '#c87060',
      success: '#7c8c6e',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'SF Mono', 'Consolas', monospace",
      fontWeight: 300,
      fontWeightBold: 600,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '16px',
      borderRadiusLg: '24px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #8a8a7a15',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },

  'zen-dark': {
    id: 'zen-dark',
    name: 'Dark Zen',
    variant: 'dark',
    colors: {
      background: '#1a1e1a',
      surface: '#252a24',
      surfaceHover: '#2e342c',
      primary: '#8fa880',
      secondary: '#c4956a',
      accent: '#d4a574',
      text: '#d8d4c8',
      textMuted: '#8a8878',
      border: '#4a4a3e',
      shadow: '#00000040',
      cardBg: '#252a24',
      cardBorder: '#4a4a3e',
      connectionLine: '#8fa880',
      selectionStroke: '#c4956a',
      danger: '#c87060',
      success: '#8fa880',
    },
    typography: {
      fontFamily: "'system-ui', '-apple-system', 'Helvetica Neue', sans-serif",
      fontFamilyMono: "'SF Mono', 'Consolas', monospace",
      fontWeight: 300,
      fontWeightBold: 600,
      lineHeight: 1.6,
      fontSize: { xs: '0.7rem', sm: '0.85rem', md: '0.95rem', lg: '1.2rem', xl: '1.5rem', xxl: '2rem' },
    },
    decorations: {
      borderRadius: '16px',
      borderRadiusLg: '24px',
      borderWidth: '1px',
      shadowStyle: '0 2px 12px #00000030',
      buttonStyle: 'soft',
      cardStyle: 'rounded',
    },
  },
};
